//! Windows main-thread stack: 1 MiB there against 8 MiB everywhere else.
//!
//! A deeply nested program (e.g. 65 nested function literals, past the
//! parser's own block budget) overflows the small Windows main stack in debug
//! builds while Linux diagnoses it cleanly — so the same test is green on one
//! platform and an abort on the other, for no reason in the language itself.
//! Reserving the Linux-sized stack on Windows aligns the two: virtual address
//! space only, committed on demand, zero cost unless deeply recursed into.
//! Non-Windows targets are untouched.

/// The default number of user function calls that may be active at once.
/// Exceeding it is a `RuntimeError`, not a Rust stack overflow.
///
/// This is the *only* copy: `build.rs` writes it into `$OUT_DIR/stack_budget.rs`
/// and `src/interpreter.rs` includes that file, so the interpreter cannot
/// compile against a different number from the one the linker sizes a stack by.
/// A build script cannot `use` the crate it builds — that is the cycle — so the
/// one that has to know first is this one, and the crate reads its answer back.
const MAX_CALL_DEPTH: usize = 1000;

/// The stack one active call frame is allowed. A frame costs roughly 58 KiB in
/// an unoptimised build — six nested Rust frames per Redblue call — so
/// [`MAX_CALL_DEPTH`] needs about 60 MiB, well past the 16 MiB a main thread
/// gets by default. A limit the process cannot physically reach would turn a
/// clean `RuntimeError` back into the abort this counter exists to prevent, so
/// the interpreter runs on a thread sized from the limit, and the playground
/// links a shadow stack sized from the same product.
const STACK_BYTES_PER_CALL: usize = 256 * 1024;

fn main() {
    let generated = format!(
        "/// The default number of user function calls that may be active at once.\n\
         /// Exceeding it is a `RuntimeError`, not a Rust stack overflow.\n\
         ///\n\
         /// Generated by `build.rs`, which is where the one copy lives: the linker\n\
         /// sizes the WebAssembly shadow stack from this same number.\n\
         pub const MAX_CALL_DEPTH: usize = {MAX_CALL_DEPTH};\n\
         \n\
         /// The stack one active call frame is allowed. A frame costs roughly 58 KiB\n\
         /// in an unoptimised build, so this limit needs about 60 MiB — well past\n\
         /// what a main thread gets by default. A limit the process cannot physically\n\
         /// reach would turn a clean `RuntimeError` back into the abort this counter\n\
         /// exists to prevent, so the interpreter runs on a thread sized from it.\n\
         ///\n\
         /// Generated by `build.rs`, which multiplies this by [`MAX_CALL_DEPTH`] to\n\
         /// size that shadow stack.\n\
         pub(crate) const STACK_BYTES_PER_CALL: usize = {STACK_BYTES_PER_CALL};\n"
    );
    let out = std::path::PathBuf::from(
        std::env::var_os("OUT_DIR").expect("cargo always sets OUT_DIR for a build script"),
    );
    std::fs::write(out.join("stack_budget.rs"), generated)
        .expect("the generated stack budget should be writable");

    #[cfg(target_os = "windows")]
    {
        println!("cargo::rustc-link-arg=/STACK:8388608");
    }

    // WebAssembly shadow stack: 1 MiB by default there, against 8 MiB on a
    // Linux main thread, and there is no thread to spawn a bigger one on — so
    // the room `run_isolated` buys natively has to be linked into the one stack
    // the module has. At the default it is nowhere near enough: a Redblue
    // function that called another trapped with "memory access out of bounds",
    // which killed the whole module instance rather than returning an error.
    //
    // The size is `MAX_CALL_DEPTH * STACK_BYTES_PER_CALL` — the *same product*
    // `run_isolated` computes for its thread. That is the whole reason the
    // numbers live here and not in `interpreter.rs`: a stack sized by a
    // different number than the depth counter checks would make the two builds
    // accept and refuse different programs, which is the one thing the
    // playground must not do. A shallower stack would trap where the native
    // binary reports a catchable `Limit`; a deeper one would be wasted address
    // space, committed only as it is used.
    //
    // It is a *link* argument, not a limit the interpreter reads and not a
    // bound a program can reach. It is emitted here rather than in
    // `.cargo/config.toml` because an environment `RUSTFLAGS` — which CI sets —
    // takes precedence over `target.*.rustflags` and would silently discard it.
    // Non-wasm targets are untouched.
    //
    // The target is read from `CARGO_CFG_TARGET_ARCH` rather than a `#[cfg]`
    // because a build script is compiled for the *host*, so `cfg!(wasm32)`
    // here is false on a Linux machine cross-compiling to wasm — which is
    // exactly the case that needs the flag. The `#[cfg]` above is fine for the
    // Windows arm only because that one is always a native build.
    if std::env::var("CARGO_CFG_TARGET_ARCH").as_deref() == Ok("wasm32") {
        let stack_bytes = MAX_CALL_DEPTH * STACK_BYTES_PER_CALL;
        println!("cargo::rustc-link-arg=-zstack-size={stack_bytes}");
    }
}
